; TocinBoot v0.1 — 64-bit -> 32-bit protected-mode handoff trampoline.
;
; Assembled flat (nasm -f bin) and embedded into the loader as a byte blob
; (build/uefi/handoff32.h, generated by the Makefile). At boot the loader
; copies the blob into a fresh EfiLoaderCode page below 4 GiB, patches the
; three qword slots at TB_HANDOFF32_SLOTS_OFF (see tocinboot.c — the offsets
; there MUST match SLOTS_OFF here), and jumps to offset 0 while still in long
; mode with UEFI identity paging active.
;
; The blob is fully position-independent: all data references are
; RIP-relative in the 64-bit part, and the 32-bit part uses only registers.
; The GDT descriptor base is self-patched at run time from the blob's actual
; load address, so the loader never needs to know where the GDT landed.
;
; End state — the 32-bit entry contract of docs/BOOT_PROTOCOL.md §6.1:
;   CR0.PE=1 PG=0, EFER.LME=LMA=0, CR4.PAE=0, IF=0, DF=0,
;   CS=0x08 flat 32-bit code, DS/ES/FS/GS/SS=0x10 flat 32-bit data,
;   EAX=TOCINBOOT_REG_MAGIC, EBX=&tocinboot_info, ESP=handoff stack top,
;   entry reached by JMP (no return address).

BITS 64
ORG 0

SLOTS_OFF equ 0xC0                    ; keep in sync with tocinboot.c

start:
    cli                               ; §6: IF=0 at entry; no IDT games below

    ; Self-patch the GDT descriptor base with our run-time address, then
    ; switch to the loader-owned GDT (lives inside this BOOTLOADER page).
    lea  rax, [rel gdt]
    mov  [rel gdtr_base], rax
    lgdt [rel gdtr]
    ; The stale CS/SS selectors keep working out of the descriptor caches
    ; until the far return below reloads CS from the new GDT.

    ; Load the loader-patched handoff values. EBX and EBP survive the mode
    ; drop untouched (rdmsr/wrmsr clobber only EAX:EDX, ECX is ours).
    mov  ebx, [rel slot_info]         ; EBX = &tocinboot_info  (< 4 GiB)
    mov  ebp, [rel slot_entry]        ; EBP = kernel e_entry   (< 4 GiB)
    mov  rsp, [rel slot_stack]        ; RSP = handoff stack top, 16-aligned

    ; Far-return into the 32-bit code segment (compatibility mode first;
    ; paging is still on and identity-maps this page).
    push qword 0x08                   ; new CS
    lea  rax, [rel pm32]
    push rax                          ; new RIP (physical, < 4 GiB)
    retfq

BITS 32
pm32:
    ; Compatibility mode, CS=0x08 (L=0, D=1). Leave long mode for real:
    ; 1) CR0.PG=0  (hardware clears EFER.LMA)
    mov  eax, cr0
    and  eax, 0x7FFFFFFF
    mov  cr0, eax
    ; 2) EFER.LME=0 — rdmsr/wrmsr clobber EAX:EDX, so this happens BEFORE
    ;    the register-magic load below.
    mov  ecx, 0xC0000080              ; IA32_EFER
    rdmsr
    and  eax, 0xFFFFFEFF              ; ~LME (bit 8)
    wrmsr
    ; 3) CR4.PAE=0
    mov  eax, cr4
    and  eax, 0xFFFFFFDF              ; ~PAE (bit 5)
    mov  cr4, eax

    ; Flat 32-bit data segments everywhere.
    mov  ax, 0x10
    mov  ds, ax
    mov  es, ax
    mov  fs, ax
    mov  gs, ax
    mov  ss, ax

    cld                               ; §6: DF=0
    mov  eax, 0x70C1B007              ; TOCINBOOT_REG_MAGIC — after rdmsr!
    jmp  ebp                          ; jump-not-call: no return address

; ---- patch slots + GDT at fixed offsets ------------------------------------
    times SLOTS_OFF - ($ - $$) db 0

slot_info:  dq 0                      ; +0x00: tocinboot_info physical addr
slot_entry: dq 0                      ; +0x08: kernel entry point
slot_stack: dq 0                      ; +0x10: stack top (16-byte aligned)

gdt:
    dq 0x0000000000000000             ; 0x00: null
    dq 0x00CF9A000000FFFF             ; 0x08: code, base 0, limit 4 GiB, D=1
    dq 0x00CF92000000FFFF             ; 0x10: data, base 0, limit 4 GiB
gdt_end:

gdtr:
    dw gdt_end - gdt - 1              ; limit
gdtr_base:
    dq 0                              ; base — self-patched at run time
